### PR TITLE
1.31

### PR DESCRIPTION
**Pull request by ericgaspar**
due to technical issues (vaulwarden is no longer compatible with the current version of YunoHost (using Debian 11 "bullseye")), the package is waiting for YunoHost for Debian 12 "bookworm"

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!bookwormtestme

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!bookwormtestme

**Comment by ericgaspar** [comment]
!testme

**Comment by OniriCorpe** [comment]
!testme

**Comment by OniriCorpe** [comment]
https://github.com/dani-garcia/vaultwarden/discussions/3833#discussioncomment-6889874

**Comment by vanyasem** [comment]
1.30.3 is out https://github.com/dani-garcia/vaultwarden/releases/tag/1.30.3

**Comment by OniriCorpe** [comment]
Yes we know
But since anyone was able to fix the blocking bug, we can't provide upgrades for now and maybe until the release of ynh on bookworm

**Comment by OniriCorpe** [comment]
> Can some context be provided to explain how to reproduce the blocking bug ? Is it that lib dependency on libssl3 mentionned in the discussion #3833 on vaultwarden repo ?

yes it is

> If that is so, the sugested solution or workaround via 'vendored_openssl' var has been tested yet ?

it's not relevant here since we don't compile vaultwarden, we have to try something else

**Comment by fflorent** [comment]
@OniriCorpe 

> https://github.com/dani-garcia/vaultwarden/discussions/3833#discussioncomment-6889874 :/

Have you tried to enable the `vendored_openssl` feature or not? Is it something you would like to try? (I have good notions in Rust, I can try if that's relevant)

**Comment by ebouaziz** [comment]
Hi guys !

I don't know much about packaging YNH apps, but since the extract-binary-from-docker-image approach does not work as expected at the moment, why not try the build-from-source approach like in syncserver-rs_ynh ? The build process doesn't look bad.

Would it be an issue on smaller systems like SBCs maybe ?

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Comment by ericgaspar** [comment]
!testme

**Comment by kay0u** [comment]
!testme

**Comment by kay0u** [comment]
!testme

**Comment by kay0u** [comment]
Update tested on my server (bookworm). All went well, everything works 👍

**Comment by kay0u** [comment]
/!\ According to https://github.com/dani-garcia/vaultwarden/releases/tag/1.30.0:

> ⚠️ Note: The WebSockets service for live sync has been integrated in the main HTTP server, which means simpler proxy setups that don't require a separate rule to redirect WS traffic to port 3012. Please check the updated examples in the [wiki](https://github.com/dani-garcia/vaultwarden/wiki/Proxy-examples). It's recommended to migrate to this new setup as using the old server on port 3012 is deprecated, won't receive new features and will be removed in a future release.

So we can drop the websocket port
https://github.com/YunoHost-Apps/vaultwarden_ynh/blob/3608c4c7f8f2cb332fad0db3cf3a547c5090fcb4/conf/nginx.conf#L17-L28

**Comment by kay0u** [comment]
!testme

**Review by kay0u — APPROVED** [review]

**Pull request merged**
