### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by ericgaspar**
## Problem

- *Description of why you made this PR*

## Solution

- *And how do you fix that problem*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by Thovi98** [comment]
As there are many people complaining about Vaultwarden's mail here and on the forum, should'nt whe just merge this?

**Comment by tituspijean** [comment]
Upon upgrading, `.env` is updated but the configuration is still incorrect in the Vaultwarden admin panel. I'm guessing it is read upon first install but then it is handled in the database?

**Comment by isAAAc** [comment]
Hi, 
can't send invitation neither, 
> An error has occurred.
> SMTP client error: internal client error: No compatible authentication mechanism was found 

should i upgrade on testing branch  ?

**Comment by tituspijean** [comment]
I have just discovered that the config is actually stored in `$data_dir/vaultwarden/config.json`. We need to patch that file.

**Comment by tituspijean** [comment]
@isAAAc can you try again?

**Comment by Tagadda** [comment]
image
@tituspijean :grin:

**Comment by tituspijean** [comment]
That is... technically correct.

**Comment by Tagadda** [comment]
It worked after I manually remplaced $domain with the real one,  :)

**Comment by tituspijean** [comment]
There, fixed. :)

**Comment by tituspijean** [comment]
!testme

**Comment by Tagadda** [comment]
!!

**Comment by isAAAc** [comment]
> @isAAAc can you try again?

sorry , i just see your post, 
nope still no mail

webui tells :
```
 An error has occurred.
SMTP client error: internal client error: No compatible authentication mechanism was found 
```

**Pull request merged**
