### PR TITLE
Fix datadir

### LINKED ISSUE #164: Latest update fails
Ok, the update works but the application cannot start anymore 😅   
   
```
sudo yunohost tools upgrade apps                                                                                                                                                                                                                                                                              
Info: Now upgrading vaultwarden...                                                                                                                                                                                                                                                                                             
Info: [+...................] > Loading installation settings...                                                                                                                                                                                                                                                                
Info: [#+..................] > Checking version...                                                                                                                                                                                                                                                                             
Info: [##+.................] > Backing up the app before upgrading (may take a while)...                                                                                                                                                                                                                                       
Info: [###+................] > Stopping a systemd service...                                                                                                                                                                                                                                                                   
Info: The service vaultwarden has correctly executed the action stop.                                                                                                                                                                                                                                                          
Info: [####+...............] > Ensuring downward compatibility...                                                                                                                                                                                                                                                              
Info: [#####+..............] > Making sure dedicated system user exists...                                                                                                                                                                                                                                                     
Info: [######+.............] > Upgrading NGINX web server configuration...                                                                                                                                                                                                                                                     
Info: [#######+............] > Upgrading dependencies...                                                                                                                                                                                                                                                                       
Info: [########+...........] > Making upgrade...                                                                                                                                                                                                                                                                               
Info: [#########+..........] > Updating a configuration file...                                                                                                                                                                                                                                                                
Info: [##########+.........] > Upgrading systemd configuration...                                                                                                                                                                                                                                                              
Info: [###########+........] > Integrating service in YunoHost...                                                                                                                                                                                                                                                              
Info: [############+.......] > Starting a systemd service...                                                                                                                                                                                                                                                                   
Warning: (this may take some time)                                                                                                                                                                                                                                                                                             
Warning: The service vaultwarden didn't fully executed the action start before the timeout.                                                                                                                                                                                                                                    
Warning: Please find here an extract of the end of the log of the service vaultwarden:                                                                                                                                                                                                                                         
Warning: Jan 22 04:48:09 vaultwarden[25101]: Error: Error downloading icon: Empty response or unable find a valid icon. connect.ubisoft.com                                                                                                                                                                                    
Warning: Jan 22 04:48:31 systemd[1]: Stopping vaultwarden Server (Rust Edition)...                                                                                                                                                                                                                                             
Warning: Jan 22 04:48:31 systemd[1]: vaultwarden.service: Main process exited, code=killed, status=15/TERM                                                                                                                                                                                                                     
Warning: Jan 22 04:48:31 systemd[1]: vaultwarden.service: Succeeded.                                                                                                                                                                                                                                                           
Warning: Jan 22 04:48:31 systemd[1]: Stopped vaultwarden Server (Rust Edition).                                                                                                                                                                                                                                                
Warning: Jan 22 04:48:44 systemd[1]: Started vaultwarden Server (Rust Edition).                                                                                                                                                                                                                                                
Warning: Jan 22 04:48:44 vaultwarden[23513]: /--------------------------------------------------------------------\                                                                                                                                                                                                            
Warning: Jan 22 04:48:44 vaultwarden[23513]: |                        Starting Vaultwarden                        |                                                                                                                                                                                                            
Warning: Jan 22 04:48:44 vaultwarden[23513]: |--------------------------------------------------------------------|                                                                                                                                                                                                            
Warning: Jan 22 04:48:44 vaultwarden[23513]: | This is an *unofficial* Bitwarden implementation, DO NOT use the   |                                                                                                                                                                                                            
Warning: Jan 22 04:48:44 vaultwarden[23513]: | official channels to report bugs/features, regardless of client.   |                                                                                                                                                                                                            
Warning: Jan 22 04:48:44 vaultwarden[23513]: | Send usage/configuration questions or feature requests to:         |                                                                                                                                                                                                            
Warning: Jan 22 04:48:44 vaultwarden[23513]: |   https://vaultwarden.discourse.group/                             |                                                                                                                                                                                                            
Warning: Jan 22 04:48:44 vaultwarden[23513]: | Report suspected bugs/issues in the software itself at:            |                                                                                                                                                                                                            
Warning: Jan 22 04:48:44 vaultwarden[23513]: |   https://github.com/dani-garcia/vaultwarden/issues/new            |                                                                                                                                                                                                            
Warning: Jan 22 04:48:44 vaultwarden[23513]: \--------------------------------------------------------------------/                                                                                                                                                                                                            
Warning: Jan 22 04:48:44 vaultwarden[23513]: [INFO] No .env file found.                                                                                                                                                                                                                                                        
Warning: Jan 22 04:48:44 systemd[1]: vaultwarden.service: Main process exited, code=exited, status=1/FAILURE                                                                                                                                                                                                                   
Warning: Jan 22 04:48:44 systemd[1]: vaultwarden.service: Failed with result 'exit-code'.                                                                                                                                                                                                                                      
Info: [#############+......] > Reconfiguring Fail2Ban...                                                                                                                                                                                                                                                                       
Info: The service fail2ban has correctly executed the action reload-or-restart.                                                                                                                                                                                                                                                
Info: [##############+.....] > Reloading NGINX web server...                                                                                                                                                                                                                                                                   
Info: [###############+....] > Upgrade of vaultwarden completed                                                                                                                                                                                                                                                                
Success! vaultwarden upgraded                                                                                                                                                                                                                                                                                                  
Success! Upgrade complete  
```   
   
   
```
systemctl status vaultwarden.service 
● vaultwarden.service - vaultwarden Server (Rust Edition)
   Loaded: loaded (/etc/systemd/system/vaultwarden.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sat 2022-01-22 06:31:13 CET; 4min 7s ago
     Docs: https://github.com/dani-garcia/vaultwarden
  Process: 13179 ExecStart=/var/www/vaultwarden/live/vaultwarden (code=exited, status=1/FAILURE)
 Main PID: 13179 (code=exited, status=1/FAILURE)
```

### PR DESCRIPTION
**Pull request by Tagadda**
## Problem

- Fix #164 
- Vaultwarden can't write to `DATADIR` 
- can't find `.env` even if specified in the systemd unit.

## Solution

- Add `DATADIR` in `ReadWriteDirectories`
- Rename `vaultwarden.env` to `.env`. We don't delete `vaultwarden.env` in case someone had some custom values.

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [x] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by Tagadda** [comment]
!testme

**Comment by nathanael-h** [comment]
I did manually the modifications this PR brings (in unit file and rename the env file). And it fixes last upgrade. Even if I am not maintainer, LGTM :wink:  Thanks for your work :clap:  :clap: !

**Comment by yalh76** [comment]
!testme

**Comment by tytan652** [comment]
I did the same kriom except that I let `EnvironmentFile` as it was and it works.

**Comment by botagas** [comment]
> Many thanks @Tagadda. Like @nathanael-h I did it too and it works.
> 
> ```
> $ ssh <myyounohost>
> admin@yuno:~$ sudo -i
> root@yuno:~# vi /etc/systemd/system/vaultwarden.service
> ```
> 
> I replaced
> 
> ```
> ReadWriteDirectories=/var/www/vaultwarden/live
> EnvironmentFile=/var/www/vaultwarden/live/vaultwarden.env
> ```
> 
> by
> 
> ```
> ReadWriteDirectories=/var/www/vaultwarden/live/web-vault
> EnvironmentFile=/var/www/vaultwarden/live/.env
> ```
> 
> and (in the same file) :
> 
> ```
>    Loaded: loaded (/etc/systemd/system/vaultwarden.service; enabled; vendor preset: enabled)
>    Active: **active** (running) since Mon 2022-01-24 13:38:56 UTC; 15min ago
> ProtectHome=true
> ```
> 
> by
> 
> ```
> ProtectHome=false
> ```
> 
> then
> 
> ```
> root@yuno:~# systemctl daemon-reload
> root@yuno:~# service vaultwarden start
> root@yuno:~# service vaultwarden status
> ```
> 
> ```
> ● vaultwarden.service - vaultwarden Server (Rust Edition)
>    Loaded: loaded (/etc/systemd/system/vaultwarden.service; enabled; vendor preset: enabled)
>    Active: active (running) since Mon 2022-01-24 13:38:56 UTC; 15min ago
> ```

Did the exact same and it worked - Vaultwarden launches, no 502 error or anything. However, I cannot get new users because domain.tld/vaultwarden never loads - the circle just keeps spinning forever.

**Comment by Karnikel** [comment]
I have to agree with @tytan652! If I change "ReadWriteDirectories" AND"EnvironmentFile" to the new value, vaultwarden doesn't start. 
If I leave "EnvironmentFile" as it is, vaultwarden starts.

My YNH-Version: 4.3.6.2 (stable)

**Comment by semanticts** [comment]
Hi same problem for me. The fix works, but spining forever prevents usage of the web interface.

**Pull request merged**
